# fly.toml file generated for spring-dew-8255 on 2024-06-09T15:40:16-06:00

app = "spring-dew-8255"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gdl"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
